from dataclasses import dataclass, field
from typing import List, Optional

@dataclass
class Paper:
    """Represents a single academic paper."""
    id: str             # e.g., arXiv ID or Scopus ID
    title: str
    category: str       # e.g., 'cs.AI'
    authors: str        # Semicolon-separated
    abstract: str
    link: str
    submitted_date: str
    source: str = "arxiv"
    citations: int = 0  # Citation count (from OpenAlex/S2)
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "title": self.title,
            "category": self.category,
            "authors": self.authors,
            "abstract": self.abstract,
            "link": self.link,
            "submitted": self.submitted_date,
            "source": self.source,
            "citations": self.citations
        }

@dataclass
class TrendAnalysis:
    """Trend analysis results from a set of papers."""
    category: str
    paper_count: int
    top_keywords: List[str]
    emerging_methods: List[str]
    research_gaps: List[str]
    methodology_patterns: List[str] = field(default_factory=list)
    saturation_level: str = "growing"  # saturated | growing | emerging
    cross_pollination: List[str] = field(default_factory=list)
    ref_papers: List[Paper] = field(default_factory=list)
    confidence: int = 7  # 1-10 self-rated confidence in the analysis
    
@dataclass
class ProjectIdea:
    """A research project idea generated by the LLM."""
    idea_title: str
    field: str
    difficulty: str          # Undergraduate | Master's | PhD
    cost_estimate: str       # Free/Colab | Cloud GPU | Institutional
    cost_note: str
    why_hard: str
    resources_needed: str
    abstract: str
    methodology_hint: str    # How to approach this technically
    next_steps: str          # First 3 concrete actions to start
    key_papers: str          # 2-3 must-read papers before starting
    why_this_idea: str       # Which gap this fills and why now
    quality_score: int       # Self-evaluated 1-10
    prerequisites: str       # Skills/knowledge needed to execute
    inspired_by: str
    inspiration_title: str
    inspiration_link: str
    generated_date: str
    source_papers: List[dict] = field(default_factory=list)
    evidence_claims: List[dict] = field(default_factory=list)
    grounding_score: int = 0
    risk_flags: List[str] = field(default_factory=list)
    critique_summary: str = ""
    refinement_summary: str = ""
    novelty_claim: str = ""
    feasibility_warning: str = ""
    refined: bool = False
    fit_to_user_summary: str = ""
    misalignment_flags: List[str] = field(default_factory=list)
    user_fit_score: int = 0
    
    def to_dict(self) -> dict:
        return {
            "idea_title": self.idea_title,
            "field": self.field,
            "difficulty": self.difficulty,
            "cost_estimate": self.cost_estimate,
            "cost_note": self.cost_note,
            "why_hard": self.why_hard,
            "resources_needed": self.resources_needed,
            "abstract": self.abstract,
            "methodology_hint": self.methodology_hint,
            "next_steps": self.next_steps,
            "key_papers": self.key_papers,
            "why_this_idea": self.why_this_idea,
            "quality_score": self.quality_score,
            "prerequisites": self.prerequisites,
            "inspired_by": self.inspired_by,
            "inspiration_title": self.inspiration_title,
            "inspiration_link": self.inspiration_link,
            "generated_date": self.generated_date,
            "source_papers": self.source_papers,
            "evidence_claims": self.evidence_claims,
            "grounding_score": self.grounding_score,
            "risk_flags": self.risk_flags,
            "critique_summary": self.critique_summary,
            "refinement_summary": self.refinement_summary,
            "novelty_claim": self.novelty_claim,
            "feasibility_warning": self.feasibility_warning,
            "refined": self.refined,
            "fit_to_user_summary": self.fit_to_user_summary,
            "misalignment_flags": self.misalignment_flags,
            "user_fit_score": self.user_fit_score,
        }


@dataclass
class ReviewCluster:
    """A thematic cluster of papers in Review Mode."""
    name: str
    paper_count: int
    methodology_summary: str
    key_findings: str
    gaps: str
    keywords: List[str] = field(default_factory=list)
    papers: List[dict] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "paper_count": self.paper_count,
            "methodology_summary": self.methodology_summary,
            "key_findings": self.key_findings,
            "gaps": self.gaps,
            "keywords": self.keywords,
            "papers": self.papers,
        }


@dataclass
class ReviewOutput:
    """Complete output of Review Mode pipeline."""
    topic: str
    paper_count: int
    clusters: List[ReviewCluster]
    timeline: str
    debates: str
    open_questions: List[str]
    reading_list: List[dict]

    def to_dict(self) -> dict:
        return {
            "topic": self.topic,
            "paper_count": self.paper_count,
            "clusters": [c.to_dict() for c in self.clusters],
            "timeline": self.timeline,
            "debates": self.debates,
            "open_questions": self.open_questions,
            "reading_list": self.reading_list,
        }
